setwd('H:\\Machine Learning\\Tradeshift-Text-Classification')
# library(data.table)
# train <- fread("Data/train.csv")
# train <- data.frame(train)
train <- read.csv("Data/train.csv", as.is=T)
dim(train)
test <- read.csv("Data/test.csv", as.is=T)
dim(test)
labels <- read.csv("Data/trainLabels.csv", as.is=T)
dim(labels)
save(train, file='train.RData')
save(test, file='test.RData')
save(labels, file='labels.RData')

gc()

system.time(load('Data/train.RData'))
system.time(load('Data/test.RData'))
system.time(load('Data/labels.RData'))
